language: python
python:
  - "3.9"
# command to install dependencies
install:
  - sudo apt-get install ncbi-blast+ bowtie
  - pip install -e .[reports,tests]
# command to run tests
script:
  - python -m pytest -v --cov dnachisel --cov-report term-missing

after_success:
  - coveralls
