from collections import defaultdict

def reverse_table(table):
    """ Return a dictionary {v1: [k1a, k1b,...]} where k1a, k1b are all
    the keys of table such that table[k1]=v1.
    """
    new_table = defaultdict(lambda: [])
    for (k, v) in table.items():
        new_table[v].append(k)
    return dict(new_table)


COMPLEMENTS = {"A":"T", "T":"A", "C":"G", "G":"C"}

NUCLEOTIDE_TO_REGEXPR = {
    "A": "[A]",
    "B": "[BCGKSTY]",
    "C": "[C]",
    "D":  "[ADGKRTW]",
    "G": "[G]",
    "H": "[ACHMTWY]",
    "K": "[GKT]",
    "M": "[ACM]",
    "N": "[ABCDGHKMNRSTVWY]",
    "R": "[AGR]",
    "S": "[CGS]",
    "T": "[T]",
    "V": "[ACGMRSV]",
    "W": "[ATW]",
    "Y": "[CTY]",
}


AA_LONGNAMES = {
    "A": "Ala", "B": "Unk", "C": "Cys",
    "D": "Asp", "E": "Glu", "F": "Phe",
    "G": "Gly", "H": "His", "I": "Ile",
    "J": "Unk", "K": "Lys", "L": "Leu",
    "M": "Met", "N": "Asn", "O": "Unk",
    "P": "Pro", "Q": "Gln", "R": "Arg",
    "S": "Ser", "T": "Thr", "U": "Unk",
    "V": "Val", "W": "Trp", "X": "Unk",
    "Y": "Tyr", "Z": "Unk", "*": "Stp"
}


CODON_TRANSLATIONS = {
    "TTT" : "F",   "TTC" : "F",   "TTA" : "L",   "TTG" : "L",
    "CTT" : "L",   "CTC" : "L",   "CTA" : "L",   "CTG" : "L",
    "ATT" : "I",   "ATC" : "I",   "ATA" : "I",   "ATG" : "M",
    "GTT" : "V",   "GTC" : "V",   "GTA" : "V",   "GTG" : "V",
    "TCT" : "S",   "TCC" : "S",   "TCA" : "S",   "TCG" : "S",
    "CCT" : "P",   "CCC" : "P",   "CCA" : "P",   "CCG" : "P",
    "ACT" : "T",   "ACC" : "T",   "ACA" : "T",   "ACG" : "T",
    "GCT" : "A",   "GCC" : "A",   "GCA" : "A",   "GCG" : "A",
    "TAT" : "Y",   "TAC" : "Y",   "TAA" : "*",   "TAG" : "*",
    "CAT" : "H",   "CAC" : "H",   "CAA" : "Q",   "CAG" : "Q",
    "AAT" : "N",   "AAC" : "N",   "AAA" : "K",   "AAG" : "K",
    "GAT" : "D",   "GAC" : "D",   "GAA" : "E",   "GAG" : "E",
    "TGT" : "C",   "TGC" : "C",   "TGA" : "*",   "TGG" : "W",
    "CGT" : "R",   "CGC" : "R",   "CGA" : "R",   "CGG" : "R",
    "AGT" : "S",   "AGC" : "S",   "AGA" : "R",   "AGG" : "R",
    "GGT" : "G",   "GGC" : "G",   "GGA" : "G",   "GGG" : "G"
}

CODONS_SEQUENCES = reverse_table(CODON_TRANSLATIONS)


CODON_USAGE = {

    "S. cerevisiae": {


        "TTT" : 0.19,   "TTC" : 1.81,   "TTA" : 0.49,   "TTG" : 5.34,
        "CTT" : 0.02,   "CTC" : 0.00,   "CTA" : 0.15,   "CTG" : 0.02,
        "ATT" : 1.26,   "ATC" : 1.74,   "ATA" : 0.00,   "ATG" : 1.00,
        "GTT" : 2.07,   "GTC" : 1.91,   "GTA" : 0.00,   "GTG" : 0.02,
        "TCT" : 3.26,   "TCC" : 2.42,   "TCA" : 0.08,   "TCG" : 0.02,
        "CCT" : 0.21,   "CCC" : 0.02,   "CCA" : 3.77,   "CCG" : 0.00,
        "ACT" : 1.83,   "ACC" : 2.15,   "ACA" : 0.00,   "ACG" : 0.01,
        "GCT" : 3.09,   "GCC" : 0.89,   "GCA" : 0.03,   "GCG" : 0.00,
        "TAT" : 0.06,   "TAC" : 1.94,   "TAA" : 1.00,   "TAG" : 0.00,
        "CAT" : 0.32,   "CAC" : 1.68,   "CAA" : 1.98,   "CAG" : 0.02,
        "AAT" : 0.06,   "AAC" : 1.94,   "AAA" : 0.16,   "AAG" : 1.84,
        "GAT" : 0.70,   "GAC" : 1.30,   "GAA" : 1.98,   "GAG" : 0.02,
        "TGT" : 1.80,   "TGC" : 0.20,   "TGA" : 0.00,   "TGG" : 1.00,
        "CGT" : 0.63,   "CGC" : 0.00,   "CGA" : 0.00,   "CGG" : 0.00,
        "AGT" : 0.06,   "AGC" : 0.16,   "AGA" : 5.37,   "AGG" : 0.00,
        "GGT" : 3.92,   "GGC" : 0.06,   "GGA" : 0.00,   "GGG" : 0.02
    },

    "E. Coli": {

        "TTT" : 0.34,   "TTC" : 1.66,   "TTA" : 0.06,   "TTG" : 0.07,
        "CTT" : 0.13,   "CTC" : 0.17,   "CTA" : 0.04,   "CTG" : 5.54,
        "ATT" : 0.48,   "ATC" : 2.51,   "ATA" : 0.01,   "ATG" : 1.00,
        "GTT" : 2.41,   "GTC" : 0.08,   "GTA" : 1.12,   "GTG" : 0.40,
        "TCT" : 2.81,   "TCC" : 2.07,   "TCA" : 0.06,   "TCG" : 0.00,
        "CCT" : 0.15,   "CCC" : 0.02,   "CCA" : 0.42,   "CCG" : 3.41,
        "ACT" : 1.87,   "ACC" : 1.91,   "ACA" : 0.10,   "ACG" : 0.12,
        "GCT" : 2.02,   "GCC" : 0.18,   "GCA" : 1.09,   "GCG" : 0.71,
        "TAT" : 0.38,   "TAC" : 1.63,   "TAA" : 1.00,   "TAG" : 1.00,
        "CAT" : 0.45,   "CAC" : 1.55,   "CAA" : 0.12,   "CAG" : 1.88,
        "AAT" : 0.02,   "AAC" : 1.98,   "AAA" : 1.63,   "AAG" : 0.37,
        "GAT" : 0.51,   "GAC" : 1.49,   "GAA" : 1.64,   "GAG" : 0.36,
        "TGT" : 0.60,   "TGC" : 1.40,   "TGA" : 1.00,   "TGG" : 1.00,
        "CGT" : 4.47,   "CGC" : 1.53,   "CGA" : 0.00,   "CGG" : 0.00,
        "AGT" : 0.13,   "AGC" : 0.93,   "AGA" : 0.00,   "AGG" : 0.00,
        "GGT" : 2.27,   "GGC" : 1.68,   "GGA" : 0.00,   "GGG" : 0.04
    },

    "H. Sapiens": {

        "TTT" : 0.27,   "TTC" : 1.73,   "TTA" : 0.05,   "TTG" : 0.31,
        "CTT" : 0.20,   "CTC" : 1.42,   "CTA" : 0.15,   "CTG" : 3.88,
        "ATT" : 0.45,   "ATC" : 2.43,   "ATA" : 0.12,   "ATG" : 1.00,
        "GTT" : 0.09,   "GTC" : 1.03,   "GTA" : 0.11,   "GTG" : 2.78,
        "TCT" : 0.45,   "TCC" : 2.09,   "TCA" : 0.26,   "TCG" : 0.68,
        "CCT" : 0.58,   "CCC" : 2.02,   "CCA" : 0.36,   "CCG" : 1.04,
        "ACT" : 0.36,   "ACC" : 2.37,   "ACA" : 0.36,   "ACG" : 0.92,
        "GCT" : 0.45,   "GCC" : 2.38,   "GCA" : 0.36,   "GCG" : 0.82,
        "TAT" : 0.34,   "TAC" : 1.66,   "TAA" : 1.00,   "TAG" : 1.00,
        "CAT" : 0.30,   "CAC" : 1.70,   "CAA" : 0.21,   "CAG" : 1.79,
        "AAT" : 0.33,   "AAC" : 1.67,   "AAA" : 0.34,   "AAG" : 1.66,
        "GAT" : 0.36,   "GAC" : 1.64,   "GAA" : 0.26,   "GAG" : 1.74,
        "TGT" : 0.42,   "TGC" : 1.58,   "TGA" : 1.00,   "TGG" : 1.00,
        "CGT" : 0.38,   "CGC" : 2.72,   "CGA" : 0.31,   "CGG" : 1.53,
        "AGT" : 0.31,   "AGC" : 2.22,   "AGA" : 0.22,   "AGG" : 0.84,
        "GGT" : 0.34,   "GGC" : 2.32,   "GGA" : 0.29,   "GGG" : 1.05
    },

    "C. elegans": {

        "TTT" : 0.72,   "TTC" : 1.28,   "TTA" : 0.45,   "TTG" : 1.35,
        "CTT" : 1.86,   "CTC" : 1.38,   "CTA" : 0.34,   "CTG" : 0.63,
        "ATT" : 1.52,   "ATC" : 1.23,   "ATA" : 0.25,   "ATG" : 1.00,
        "GTT" : 1.67,   "GTC" : 1.11,   "GTA" : 0.52,   "GTG" : 0.70,
        "TCT" : 1.47,   "TCC" : 0.98,   "TCA" : 1.44,   "TCG" : 0.83,
        "CCT" : 0.52,   "CCC" : 0.23,   "CCA" : 2.75,   "CCG" : 0.51,
        "ACT" : 1.34,   "ACC" : 1.02,   "ACA" : 1.15,   "ACG" : 0.49,
        "GCT" : 1.64,   "GCC" : 1.06,   "GCA" : 0.99,   "GCG" : 0.31,
        "TAT" : 0.97,   "TAC" : 1.03,   "TAA" : 1.00,   "TAG" : 1.00,
        "CAT" : 1.13,   "CAC" : 0.87,   "CAA" : 1.39,   "CAG" : 0.61,
        "AAT" : 1.10,   "AAC" : 0.90,   "AAA" : 0.84,   "AAG" : 1.16,
        "GAT" : 1.36,   "GAC" : 0.64,   "GAA" : 1.15,   "GAG" : 0.85,
        "TGT" : 1.14,   "TGC" : 0.86,   "TGA" : 1.00,   "TGG" : 1.00,
        "CGT" : 1.84,   "CGC" : 0.73,   "CGA" : 1.07,   "CGG" : 0.31,
        "AGT" : 0.76,   "AGC" : 0.52,   "AGA" : 1.79,   "AGG" : 0.26,
        "GGT" : 0.70,   "GGC" : 0.28,   "GGA" : 2.85,   "GGG" : 0.16
    },

    "D. melanogaster": {

        "TTT" : 0.12,   "TTC" : 1.88,   "TTA" : 0.03,   "TTG" : 0.69,
        "CTT" : 0.25,   "CTC" : 0.72,   "CTA" : 0.06,   "CTG" : 4.25,
        "ATT" : 0.74,   "ATC" : 2.26,   "ATA" : 0.00,   "ATG" : 1.00,
        "GTT" : 0.56,   "GTC" : 1.59,   "GTA" : 0.06,   "GTG" : 1.79,
        "TCT" : 0.87,   "TCC" : 2.74,   "TCA" : 0.04,   "TCG" : 1.17,
        "CCT" : 0.42,   "CCC" : 2.73,   "CCA" : 0.62,   "CCG" : 0.23,
        "ACT" : 0.65,   "ACC" : 3.04,   "ACA" : 0.10,   "ACG" : 0.21,
        "GCT" : 0.95,   "GCC" : 2.82,   "GCA" : 0.09,   "GCG" : 0.14,
        "TAT" : 0.23,   "TAC" : 1.77,   "TAA" : 1.00,   "TAG" : .00,
        "CAT" : 0.29,   "CAC" : 1.71,   "CAA" : 0.03,   "CAG" : 1.97,
        "AAT" : 0.13,   "AAC" : 1.87,   "AAA" : 0.06,   "AAG" : 1.94,
        "GAT" : 0.90,   "GAC" : 1.10,   "GAA" : 0.19,   "GAG" : 1.81,
        "TGT" : 0.07,   "TGC" : 1.93,   "TGA" : 1.00,   "TGG" : 1.00,
        "CGT" : 2.65,   "CGC" : 3.07,   "CGA" : 0.07,   "CGG" : 0.00,
        "AGT" : 0.04,   "AGC" : 1.13,   "AGA" : 0.00,   "AGG" : 0.21,
        "GGT" : 1.34,   "GGC" : 1.66,   "GGA" : 0.99,   "GGG" : 0.00
    },

    "B. subtilis": {

        "TTT" : 0.70,   "TTC" : 1.30,   "TTA" : 2.71,   "TTG" : 0.00,
        "CTT" : 2.13,   "CTC" : 0.00,   "CTA" : 1.16,   "CTG" : 0.00,
        "ATT" : 0.91,   "ATC" : 1.96,   "ATA" : 0.13,   "ATG" : 1.00,
        "GTT" : 1.88,   "GTC" : 0.25,   "GTA" : 1.38,   "GTG" : 0.50,
        "TCT" : 3.45,   "TCC" : 0.00,   "TCA" : 1.50,   "TCG" : 0.00,
        "CCT" : 2.29,   "CCC" : 0.00,   "CCA" : 1.14,   "CCG" : 0.57,
        "ACT" : 2.21,   "ACC" : 0.00,   "ACA" : 1.38,   "ACG" : 0.41,
        "GCT" : 2.94,   "GCC" : 0.08,   "GCA" : 0.60,   "GCG" : 0.38,
        "TAT" : 0.50,   "TAC" : 1.50,   "TAA" : 0.00,   "TAG" : 0.00,
        "CAT" : 2.00,   "CAC" : 0.00,   "CAA" : 1.71,   "CAG" : 0.29,
        "AAT" : 0.47,   "AAC" : 1.53,   "AAA" : 1.83,   "AAG" : 0.17,
        "GAT" : 0.53,   "GAC" : 1.47,   "GAA" : 1.40,   "GAG" : 0.60,
        "TGT" : 0.00,   "TGC" : 2.00,   "TGA" : 0.00,   "TGG" : 1.00,
        "CGT" : 3.11,   "CGC" : 1.78,   "CGA" : 1.00,   "CGG" : 0.00,
        "AGT" : 0.45,   "AGC" : 0.60,   "AGA" : 1.11,   "AGG" : 0.00,
        "GGT" : 1.38,   "GGC" : 0.97,   "GGA" : 1.66,   "GGG" : 0.00
    }
}

OTHER_BASES = {
    "A": ["T", "G", "C"],
    "T": ["A", "G", "C"],
    "G": ["T", "A", "C"],
    "C": ["T", "G", "A"],
}


ENZYMES_SITES= {

    "AarI": "CACCTGC(4/8)",
    "AatII": "GACGT^C",
    "AccI": "GT^MKAC",
    "Acc65I": "G^GTACC",
    "AciI": "CCGC(-3/-1)",
    "AclI": "AA^CGTT",
    "AcuI": "CTGAAG(16/14)",
    "AfeI": "AGC^GCT",
    "AflII": "C^TTAAG",
    "AflIII": "A^CRYGT",
    "AgeI": "A^CCGGT",
    "AhdI": "GACNNN^NNGTC",
    "AleI": "CACNN^NNGTG",
    "AluI": "AG^CT",
    "AlwI": "GGATC(4/5)",
    "AlwNI": "CAGNNN^CTG",
    "ApaI": "GGGCC^C",
    "ApaLI": "G^TGCAC",
    "ApoI": "R^AATTY",
    "AscI": "GG^CGCGCC",
    "AseI": "AT^TAAT",
    "AsiSI": "GCGAT^CGC",
    "AsuII": "TT^CGAA",
    "AvaI": "C^YCGRG",
    "AvaII": "G^GWCC",
    "AvrII": "C^CTAGG",
    "BaeGI": "GKGCM^C",
    "BamHI": "G^GATCC",
    "BanI": "G^GYRCC",
    "BanII": "GRGCY^C",
    "BbsI": "GAAGAC(2/6)",
    "BbvCI": "CCTCAGC(-5/-2)",
    "BbvI": "GCAGC(8/12)",
    "BccI": "CCATC(4/5)",
    "BceAI": "ACGGC(12/14)",
    "BciVI": "GTATCC(6/5)",
    "BclI": "T^GATCA",
    "BfaI": "C^TAG",
    "BfuAI": "ACCTGC(4/8)",
    "BglI": "GCCNNNN^NGGC",
    "BglII": "A^GATCT",
    "BlpI": "GC^TNAGC",
    "BmgBI": "CACGTC(-3/-3)",
    "BmrI": "ACTGGG(5/4)",
    "BmtI": "GCTAG^C",
    "BpmI": "CTGGAG(16/14)",
    "Bpu10I": "CCTNAGC(-5/-2)",
    "BpuEI": "CTTGAG(16/14)",
    "BsaAI": "YAC^GTR",
    "BsaBI": "GATNN^NNATC",
    "BsaHI": "GR^CGYC",
    "BsaI": "GGTCTC(1/5)",
    "BsaJI": "C^CNNGG",
    "BsaWI": "W^CCGGW",
    "BseMII": "CTCAG(10/8)",
    "BseRI": "GAGGAG(10/8)",
    "BseYI": "CCCAGC(-5/-1)",
    "BsgI": "GTGCAG(16/14)",
    "BsiEI": "CGRY^CG",
    "BsiHKAI": "GWGCW^C",
    "BsiWI": "C^GTACG",
    "BslI": "CCNNNNN^NNGG",
    "BsmAI": "GTCTC(1/5)",
    "BsmBI": "CGTCTC(1/5)",
    "BsmFI": "GGGAC(10/14)",
    "BsmI": "GAATGC(1/-1)",
    "BsoBI": "C^YCGRG",
    "Bsp1286I": "GDGCH^C",
    "BspCNI": "CTCAG(9/7)",
    "BspEI": "T^CCGGA",
    "BspHI": "T^CATGA",
    "BspMI": "ACCTGC(4/8)",
    "BspQI": "GCTCTTC(1/4)",
    "BsrBI": "CCGCTC(-3/-3)",
    "BsrDI": "GCAATG(2/0)",
    "BsrFI": "R^CCGGY",
    "BsrGI": "T^GTACA",
    "BsrI": "ACTGG(1/-1)",
    "BssHII": "G^CGCGC",
    "BssKI": "^CCNGG",
    "BssSI": "C^ACGAG",
    "BstAPI": "GCANNNN^NTGC",
    "BstBI": "TT^CGAA",
    "BstEII": "G^GTNACC",
    "BstNI": "CC^WGG",
    "BstUI": "CG^CG",
    "BstXI": "CCANNNNN^NTGG",
    "BstYI": "R^GATCY",
    "BstZ17I": "GTA^TAC",
    "Bsu36I": "CC^TNAGG",
    "BtgI": "C^CRYGG",
    "BtgZI": "GCGATG(10/14)",
    "BtrI": "CACGTC(-3/-3)",
    "BtsCI": "GGATG(2/0)",
    "BtsI": "GCAGTG(2/0)",
    "Cac8I": "GCN^NGC",
    "ClaI": "AT^CGAT",
    "CviAII": "C^ATG",
    "CviKI": "RG^CY",
    "CviQI": "G^TAC",
    "DdeI": "C^TNAG",
    "DpnI": "GA^TC",
    "DpnII": "^GATC",
    "DraI": "TTT^AAA",
    "DraIII": "CACNNN^GTG",
    "DrdI": "GACNNNN^NNGTC",
    "EaeI": "Y^GGCCR",
    "EagI": "C^GGCCG",
    "EarI": "CTCTTC(1/4)",
    "EciI": "GGCGGA(11/9)",
    "Eco31I": "GGTCTC(1/5)",
    "Eco53KI": "GAG^CTC",
    "Eco57MI": "CTGRAG(16/14)",
    "EcoNI": "CCTNN^NNNAGG",
    "EcoO109I": "RG^GNCCY",
    "EcoP15I": "CAGCAG(25/27)",
    "EcoRI": "G^AATTC",
    "EcoRII": "^CCWGG",
    "EcoRV": "GAT^ATC",
    "Esp3I": "CGTCTC(1/5)",
    "FatI": "^CATG",
    "FauI": "CCCGC(4/6)",
    "Fnu4HI": "GC^NGC",
    "FokI": "GGATG(9/13)",
    "FseI": "GGCCGG^CC",
    "FspAI": "RTGC^GCAY",
    "FspI": "TGC^GCA",
    "HaeII": "RGCGC^Y",
    "HaeIII": "GG^CC",
    "HgaI": "GACGC(5/10)",
    "HhaI": "GCG^C",
    "HincII": "GTY^RAC",
    "HindIII": "A^AGCTT",
    "HinfI": "G^ANTC",
    "HinP1I": "G^CGC",
    "HpaI": "GTT^AAC",
    "HpaII": "C^CGG",
    "HphI": "GGTGA(8/7)",
    "Hpy166II": "GTN^NAC",
    "Hpy188I": "TCN^GA",
    "Hpy188III": "TC^NNGA",
    "Hpy99I": "CGWCG^",
    "HpyAV": "CCTTC(6/5)",
    "HpyCH4III": "ACN^GT",
    "HpyCH4IV": "A^CGT",
    "HpyCH4V": "TG^CA",
    "KasI": "G^GCGCC",
    "KpnI": "GGTAC^C",
    "MaeI": "C^TAG",
    "MaeII": "A^CGT",
    "MaeIII": "^GTNAC",
    "MboII": "GAAGA(8/7)",
    "MfeI": "C^AATTG",
    "MluI": "A^CGCGT",
    "MlyI": "GAGTC(5/5)",
    "MmeI": "TCCRAC(20/18)",
    "MnlI": "CCTC(7/6)",
    "MscI": "TGG^CCA",
    "MseI": "T^TAA",
    "MslI": "CAYNN^NNRTG",
    "MspA1I": "CMG^CKG",
    "MwoI": "GCNNNNN^NNGC",
    "NaeI": "GCC^GGC",
    "NarI": "GG^CGCC",
    "NciI": "CC^SGG",
    "NcoI": "C^CATGG",
    "NdeI": "CA^TATG",
    "NgoMIV": "G^CCGGC",
    "NheI": "G^CTAGC",
    "NlaIII": "CATG^",
    "NlaIV": "GGN^NCC",
    "NmeAIII": "GCCGAG(21/19)",
    "NotI": "GC^GGCCGC",
    "NruI": "TCG^CGA",
    "NsiI": "ATGCA^T",
    "NspI": "RCATG^Y",
    "PacI": "TTAAT^TAA",
    "PasI": "CC^CWGGG",
    "PciI": "A^CATGT",
    "PflFI": "GACN^NNGTC",
    "PflMI": "CCANNNN^NTGG",
    "PfoI": "T^CCNGGA",
    "PleI": "GAGTC(4/5)",
    "PmeI": "GTTT^AAAC",
    "PpuMI": "RG^GWCCY",
    "PshAI": "GACNN^NNGTC",
    "PsiI": "TTA^TAA",
    "PspGI": "^CCWGG",
    "PspOMI": "G^GGCCC",
    "PspXI": "VC^TCGAGB",
    "PstI": "CTGCA^G",
    "PvuI": "CGAT^CG",
    "PvuII": "CAG^CTG",
    "RsaI": "GT^AC",
    "RsrII": "CG^GWCCG",
    "SacI": "GAGCT^C",
    "SacII": "CCGC^GG",
    "SalI": "G^TCGAC",
    "SanDI": "GG^GWCCC",
    "Sau96I": "G^GNCC",
    "SbfI": "CCTGCA^GG",
    "ScaI": "AGT^ACT",
    "ScrFI": "CC^NGG",
    "SexAI": "A^CCWGGT",
    "SfaNI": "GCATC(5/9)",
    "SfcI": "C^TRYAG",
    "SfiI": "GGCCNNNN^NGGCC",
    "SfoI": "GGC^GCC",
    "SgrAI": "CR^CCGGYG",
    "SmaI": "CCC^GGG",
    "SmlI": "C^TYRAG",
    "SnaBI": "TAC^GTA",
    "SpeI": "A^CTAGT",
    "SphI": "GCATG^C",
    "SrfI": "GCCC^GGGC",
    "SspI": "AAT^ATT",
    "StuI": "AGG^CCT",
    "StyI": "C^CWWGG",
    "SwaI": "ATTT^AAAT",
    "TaiI": "ACGT^",
    "TaqI": "T^CGA",
    "TatI": "W^GTACW",
    "TauI": "GCSG^C",
    "TfiI": "G^AWTC",
    "TseI": "G^CWGC",
    "Tsp45I": "^GTSAC",
    "Tsp509I": "^AATT",
    "TspDTI": "ATGAA(11/9)",
    "TspGWI": "ACGGA(11/9)",
    "TspMI": "C^CCGGG",
    "TspRI": "CASTGNN^",
    "Tth111I": "GACN^NNGTC",
    "XbaI": "T^CTAGA",
    "XcmI": "CCANNNNN^NNNNTGG",
    "XhoI": "C^TCGAG",
    "XhoII": "R^GATCY",
    "XmaI": "C^CCGGG",
    "XmnI": "GAANN^NNTTC",
    "ZraI": "GAC^GTC"
}
