#!/usr/bin/env python

"""
DnaChisel Command Line Interface

Usage:
  dnachisel <source> <target> [--circular]

Where ``source`` is a fasta or Genbank file, and target can be one of:
- A folder name or a zip name (extension .zip). In this case a complete report
  along with the sequence will be generated.

Note: this CLI will be developed on a per-request basis, so don't hesitate to
ask for more handles and options on Github
(https://github.com/Edinburgh-Genome-Foundry/DnaChisel/issues)
"""

from docopt import docopt
from dnachisel import DnaOptimizationProblem, CircularDnaOptimizationProblem

if __name__ == "__main__":
    params = docopt(__doc__)
    source, target = params["<source>"], params["<target>"]
    if params['--circular']:
        problem_class = DnaOptimizationProblem
    else:
        problem_class = CircularDnaOptimizationProblem
    problem = problem_class.from_record(source)
    problem.max_random_iters = 10000
    print(
        '\n\nBefore optimization:\n\n',
        problem.constraints_text_summary(),
        problem.objectives_text_summary()
    )

    if target.lower().endswith('.gb'):
        problem.resolve_constraints()
        problem.optimize()
    
    else:
        problem.optimize_with_report(target)

    print(
        '\n\nAfter optimization:\n\n',
        problem.constraints_text_summary(),
        problem.objectives_text_summary(),
        '\n\n',
        'Result written to %s' % target
    )
