#!/usr/bin/env python

"""
DnaChisel Command Line Interface

Usage:
  dnachisel <source> <target>

Where ``source`` is a fasta or Genbank file, and target can be one of:
- A folder name or a zip name (extension .zip). In this case a complete report
  along with the sequence will be generated.
"""

from docopt import docopt
from dnachisel.reports import optimize_with_report

if __name__ == "__main__":
    params = docopt(__doc__)
    optimize_with_report(params["<target>"], record=params["<source>"],
                             max_random_iters=10000)
