name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pytest pytest-cov coveralls
          sudo apt-get install ncbi-blast+ bowtie
          
      - name: Install
        run: |
          pip install -e .[reports,tests]
      - name: Test with pytest
        run: |
          python -m pytest --cov dnachisel --cov-report term-missing
      - name: Coveralls
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
